source_locale: en
api_token: ${{ secrets.PTC_API_TOKEN }}
files:
  - file: config/locales/en.yml
    output: config/locales/{{lang}}.yml

  - file: config/locales/devise.en.yml
    output: config/locales/devise.{{lang}}.yml
